[providers]
  [providers.aws_bedrock]
    models = ["anthropic.claude-v2", "anthropic.claude-instant-v1"]

#  [providers.openai]
#    models = ["gpt-3.5-turbo", "gpt-4"]

[default]
provider = "aws_bedrock"
