services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config.toml:/app/config.toml
      - ./service.json:/app/service.json
    command: ["/app/main"]
